# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'viper-arch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for viper-arch
  pod 'AFNetworking', '~> 4.0'

end